management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
  tomcat:
    threads:
      max: 500

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: chat-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.16.4.136


#  redis:
#    database: 0
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 100
#        min-idle: 0
#        max-wait: -1
#    timeout: 5000
#    host: 172.16.2.172

#mybatis:
#  type-aliases-package: cn.edu.xmu.wishes.chat.model.po
#  mapper-locations: classpath*:cn.edu.xmu.wishes.chat.mapper/*.xml
#  configuration:
#    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true