management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: 任务中心
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/**

  redis:
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000
    host: 127.0.0.1
wishes:
  jwt:
    public:
      key: app.pub
  security:
    ignoreUrls:
      - /user/oauth/**
      - /webjars/**