management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  tomcat:
    threads:
      max: 500

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: task-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 172.16.4.136

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/wishes?serverTimezone=GMT%2B8
    username: dbuser
    password: 12345678
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

  mail:
    host: smtp.163.com
    username: oomall2_4@163.com
    password: HQQLBPJWWJRRLSXQ
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
        imap:
          ssl:
            socketFactory:
              rollback: false
      from: oomall2_4@163.com
    default-encoding: utf-8
    protocol: smtps

  redis:
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000
    host: localhost

#mybatis-plus:
#  configuration:
#    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#mybatis:
#  type-aliases-package: cn.edu.xmu.wishes.chat.model.po
#  mapper-locations: classpath*:cn.edu.xmu.wishes.chat.mapper/*.xml
#  configuration:
#    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

user:
  login:
    jwt:
      expire: 3600
    captcha:
      expire: 300

  mail:
    #邮件主题
    subject: "【wishes】注册验证码"
    #内容格式
    format: "您的验证码是：%s 5分钟内有效"
    from: "oomall2_4@163.com"

wishes:
  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub
  storage:
    active: webdav

    webdav:
      url: http://122.9.37.63/webdav/
      directory: task
      username: dev
      password: Wishes12345678
      replaceStr: /webdav