#spring:
#  main:
#    allow-bean-definition-overriding: true
#  servlet:
#    multipart:
#      enabled: true
#      max-request-size: 10MB
#  #  cloud:
#  #    nacos:
#  #      discovery:
#  #        server-addr: 172.16.4.136
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/wishes?serverTimezone=GMT%2B8
#    username: dbuser
#    password: 12345678
#    druid:
#      initial-size: 3
#      min-idle: 3
#      max-active: 100
#      max-wait: 60000
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123456
#        enabled: true
#        url-pattern: /druid/*
#
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 100
#      validation-query: select 1
#    sql-script-encoding: UTF-8
#
#wishes:
#  storage:
#    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
#    active: webdav
#    # 本地对象存储配置信息
#    local:
#      storagePath: storage
#      address: 111
#    webdav:
#      url: http://139.9.131.172/webdav/
#      directory: test
#      username: dev
#      password: Wishes12345678
#
#    # 七牛云对象存储配置信息
#    qiniu:
#      endpoint: http://r7h8py5f8.hn-bkt.clouddn.com
#      accessKey: 58XTcMlrDVSJo4ZzqN6JdX_VIz7WVA2DQ5BuRNqN
#      secretKey: 9lyx4yMthLmI9ySHBp4kcZlLyuIzpuW89mkBXimt
#      bucketName: wishes1